### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by kzzyn** [w-vi/chrome-ext-slovnikcz#4]
I have just installed this addon in the latest Firefox (67.0.4), but after highlighting word on some page there is no option to translate it in the context menu.

**Comment by kzzyn** [comment]
After Firefox update 68.0 the addon is working.

**Comment by w-vi** [comment]
Thanks a lot for reporting the issue. I personally run on the dev branch of firefox and never had issues but it has happend on some older versions too but then it started to work again after update. I am little confused on why is it happening but given it works again I will close this issue. If it happens one more time please let me know and I will try to come up with some fix. Most likely rewrite as I have no idea why it comes and goes.
